- hosts: localhost
  tasks:
  - ec2:
     key_name: Jun2KeyPair
     instance_type: t2.micro
     image: ami-035b3c7efe6d061d5
     wait: yes   
     count: 1
     instance_tags:
       Name: three
     vpc_subnet_id: subnet-ffbfdea3
     assign_public_ip: yes
     region: us-east-1
    register: ec2
  - name: set a variable for ec2's private ip
    set_fact:
     priv_ip: "{{ ec2.instances[0].private_ip }}"
  - name: Add host to group 'webservers'
    add_host:
     hostname: "{{ priv_ip }}"
     groups: webservers
  - debug:
     msg:
      - "{{ priv_ip }}"
# ex2 task to create EC2 instance and capture the output using - register
# created a task - set_fact -  to get the private ip of the new instance and store it in a variable
# created a task to register new instance in the hosts (using add_host module)
